#!/usr/bin/perl

while (<>)
{
  if (m/SHOOTER/)
  {
    @fields = split;
    $my_time = $fields[8] if ($fields[7] =~ m/time/);
    $my_motor1 = $fields[8] if ($fields[7] eq "RPM1:");
    if ($fields[7] eq "RPM2:")
    {
      print "$my_time,$my_motor1,$fields[8]\n";
    }
  }
}

